### ISSUE TITLE
Correct Typo in Blockchain Lecture 4-Accounts_and_UTXOs-slides

### ISSUE THREAD

**Issue by Krayt78** [Polkadot-Blockchain-Academy/pba-content#1031]
https://polkadot-blockchain-academy.github.io/pba-content/current/syllabus/3-Blockchain/4-Accounts_and_UTXOs-slides.html#/12
On the 12th slide, the green outlined square should have a value of 65 and not 70 according to the 10th slide.
@JoshOrndorff

**Comment by wirednkod** [comment]
Duplicate with #1029
