### ISSUE TITLE
Workshop: Start a Blockchain Network

### ISSUE THREAD

**Issue by JoshOrndorff** [Polkadot-Blockchain-Academy/pba-content#340]
The start a network activity needs to be written up more thoroughly.

A complete writeup should include
* Information about setting up the bootnode
* Requirements of the venue wifi, and a way to work around unsuitable wifi
   * Eg. Venue wifi has a too-strict firewall and won't allow nodes to peer - Instructor should have a router ready to use
* Slides or written instructions for students to follow

**Comment by wirednkod** [comment]
This is completed by https://github.com/Polkadot-Blockchain-Academy/Academy-PoW/pull/41
