### ISSUE TITLE
How to publish gh-pages privately

### ISSUE THREAD

**Issue by NukeManDan** [Polkadot-Blockchain-Academy/pba-content#763]
https://docs.github.com/en/enterprise-cloud@latest/pages/getting-started-with-github-pages/changing-the-visibility-of-your-github-pages-site

I need to figure this out for https://github.com/Polkadot-Blockchain-Academy/pba-ucb-frameles-node-template/settings/pages for example - it's public now as private is _blocked_ for some silly reason.

**Comment by wirednkod** [comment]
No need to do that anymore. Closing here
