### ISSUE TITLE
[Polkadot module] - Dead Link

### ISSUE THREAD

**Issue by wirednkod** [Polkadot-Blockchain-Academy/pba-content#880]
Link checker (https://github.com/Polkadot-Blockchain-Academy/pba-content/actions/runs/7292586300/job/19873893657?pr=878) found out that the https://rosettacode.org/wiki/Conway%27s_Game_of_Life#Rust is not working anymore. This is in Polkadot module: 7-Build_Simple_Parachain/1-Build_Simple_Parachain_Slides.md

**Comment by JoshOrndorff** [comment]
The whole rosetta code website is down right now. Maybe it will be back later.

If not, perhaps this could be adapted https://rustwasm.github.io/book/game-of-life/introduction.html

**Comment by wirednkod** [comment]
Rosetta code is back up. This can close
