### ISSUE TITLE
[Smart contracts module] Link does not exist

### ISSUE THREAD

**Issue by wirednkod** [Polkadot-Blockchain-Academy/pba-content#902]
@JoshOrndorff there is a dead link in [syllabus/4-Smart_Contracts/Outline_Standalone.md](https://github.com/Polkadot-Blockchain-Academy/pba-content/blob/main/syllabus/4-Smart_Contracts/Outline_Standalone.md) in Smart contracts module.

Can you please make sure that it is either removed or fixed?

**Comment by JoshOrndorff** [comment]
Oof, it's because I merged https://github.com/Polkadot-Blockchain-Academy/pba-content/pull/879 with failing CI. Sorry about that. I'll fix it now.

**Comment by wirednkod** [comment]
Thank you @JoshOrndorff  🙏🏽
