### ISSUE TITLE
[Blockchain module] Link does not exist

### ISSUE THREAD

**Issue by wirednkod** [Polkadot-Blockchain-Academy/pba-content#903]
@Overkillus there is a dead link in the Blockchain module:

FILE: ./syllabus/3-Blockchain/5-Econ_and_Game_Theory_in_Blockchain_slides.md
[✖] https://citeseerx.ist.psu.edu/document?repid=rep1&type=pdf&doi=7bf78054192d98e999edcdf08971a5eed42518d2 → Status: 500

Can you please make sure that it is either removed or fixed?

**Comment by JoshOrndorff** [comment]
I think citeseerx will come back soon. It is a very popular academic repository.

If it doesn't, I believe this is the same paper https://typeset.io/pdf/mining-pool-game-model-and-nash-equilibrium-analysis-for-pow-2lckzso542.pdf but @Overkillus can confirm.

**Comment by wirednkod** [comment]
Thank you @JoshOrndorff . I understand that these sites can be off for a little amount of time. 
I use this Issue more for tracking and confirmations (as you did).
Maybe f the link interested (e.g. a PDF) could be downloaded and added in a directory inside the content instead of linking an external source that may seize to exist after X amount of time?

**Comment by JoshOrndorff** [comment]
I've swapped out the links.

> downloaded and added in a directory inside the content instead of linking

If we decide to do something like this we should discuss what content is important enough to come in to our own repo. Not just start with this random one. For now I'm happy to stay the course.
