### ISSUE TITLE
[Cryptography module] Link does not exist

### ISSUE THREAD

**Issue by wirednkod** [Polkadot-Blockchain-Academy/pba-content#904]
The following links do not exist in the cryptography module:

[✖] ./materials/aes-modes-activity/ → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/syllabus/1-Cryptography/materials/aes-modes-activity'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/github/workspace/syllabus/1-Cryptography/materials/aes-modes-activity'
}
[✖] ./materials/merkle-tree-activity/ → Status: 400 [Error: ENOENT: no such file or directory, access '/github/workspace/syllabus/1-Cryptography/materials/merkle-tree-activity'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'access',
  path: '/github/workspace/syllabus/1-Cryptography/materials/merkle-tree-activity'
}

**Comment by wirednkod** [comment]
hey @coax1d and @drskalman ; Since you are the ones that are cryptography module during PBA-4, can you please elaborate what are the links above and if they should stay or be removed? 

I think, more likely, that these are left-overs.
Thank you in advance

**Comment by JoshOrndorff** [comment]
I can confirm these are leftovers. I created those two activities for Cambridge. The Merkle one has been iterated on and improved many times and a version of it is now in the graded assignment (which is in another repo). I believe the same is true for the AES modes.

**Comment by JoshOrndorff** [comment]
I removed the broken links in #908
