### ISSUE TITLE
Dead link - ink SC

### ISSUE THREAD

**Issue by wirednkod** [Polkadot-Blockchain-Academy/pba-content#923]
Link https://learn.saylor.org/mod/book/view.php?id=36341&chapterid=18921 is making the CI fail

**Comment by JoshOrndorff** [comment]
Seems like Saylor.org is kind of intermittent. I opened an issue about a link to there just the other day https://github.com/Polkadot-Blockchain-Academy/pba-content/issues/914

**Comment by fbielejec** [comment]
I'm not sure what to do with this, removing comes to my mind but this is not from my slides

**Comment by wirednkod** [comment]
This is fixed now
